Cargo.toml, README.md, src/lib.rs
I might have missed some parts of 3.0 but this should cover most of the changes.
Fixes #10
=> feat: Add definitions for language-server-protocol 3.0

Cargo.toml, src/lib.rs
Closes #14, and should allow RLS to fix rust-lang-nursery/rls#312.
=> Make ClientCapabilities.experimental field optional

Cargo.toml, src/lib.rs
When using `with` attributes optional fields need to be explicitly
marked as `default` or the deserializer will fail immediately.
https://github.com/serde-rs/serde/issues/259
cc https://github.com/rust-lang-nursery/rls/issues/312
=> fix: Allow the InitializeParams::rootUri to be missing

src/lib.rs
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_hover
This is a breaking change. Might need to upgrade version number as well. Just not sure which part of version should bump.
=> Hover contents could be single entry or multiple entries.

src/lib.rs
From the protocol, seems there is only `workspace/applyEdit`, which also
has the exact same comment.
=> Fix applyEdit method name.

src/lib.rs
Is there a reason, why these types implement `ParialEq` but not `Eq`? I added derive Eq for all types which can implement it. Types which contain a `serde_json::Value` or `f64` and transitive types cannot implement it.
=> Derive `Eq` where possible

src/lib.rs
The Position type has a sensible ordering, first by line then by character. This PR implements PartialOrd and Ord for Position. Because Ord requires Eq, this PR requires https://github.com/gluon-lang/languageserver-types/pull/27.
=> Implement Ord for Position

src/lib.rs, src/notification.rs, src/request.rs
Attempt at #19. I took some sweet time with this, sorry for doing it so late.
Currently LSP spec provides new `CompletionParams` and `CompletionContext` types to be used with Completion Request, so I used LSP commit in the comment and used [`TextDocumentPositionParams`](https://github.com/gluon-lang/languageserver-types/compare/master...Xanewok:message-traits?expand=1#diff-b4aea3e418ccdb71239b96952d9cddb6R1643) as param type instead.
@Marwes does this align with what you wanted in #19?
=> Message traits

Cargo.toml, src/lib.rs, src/notification.rs, src/request.rs
Implements the mapping I hinted at in https://github.com/gluon-lang/languageserver-types/pull/29#issuecomment-347686297. The idea is that one can just grep for the actual method names that are called when searching for how/if a method is implemented instead of guessing at what a method's "type" are called.
Based on #30 
cc @Xanewok
=>  feat: Add macros which map from RPC method strings to the RPC traits 

src/lib.rs
See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textdocumentitem
=> languageId and version does not need to be optional

src/lib.rs
https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#versionedtextdocumentidentifier
=> VersionedTextDocumentIdentifier version could be null.

Cargo.toml, src/lib.rs
This is caused by using `with` for the field which causes the default
behaviour of allowing a missing fields to be transformed into `None`
Fixes #39
=>  fix: Allow the changes field to be omitted

src/lib.rs
There seems to be some discrepancy around field being ommited and null
value. And null fields are breaking at least some fragile language
servers.
- https://github.com/autozimu/LanguageClient-neovim/issues/265
- https://github.com/jacobdufault/cquery/issues/247
=> Skip field when it is null/none.

src/notification.rs, src/request.rs
These are server->client requests (https://microsoft.github.io/language-server-protocol/specification#client_registerCapability), I must've made a mistake last time I implemented traits for messages.
Also added separating whitespace and reordered workspace macros in request.rs to mimic order given [here](https://microsoft.github.io/language-server-protocol/specification).
=> Move client/(un)registerCapability to requests

src/lib.rs
These comments have been copy-pasted from the spec so things are
sometimes wrong. The JSON in question don't add any information that
can't be inferred from the definition so it is removed.
Closes #61
=> Remove mention of JSON that does not exist

src/lib.rs
Add `skip_serializing_if` attribute to all fields that are optional and can't be null - as of 3.8.0 version of LSP specification.
=> Skip serializing optional fields.

Cargo.toml, src/lib.rs
The former isn't maintained anymore which brings in outdated
dependencies.
=> Replace enum_primitive by num-derive

src/lib.rs
The `ServerCapabilities` struct was missing some items that are present in the protocol as of version 3.6.0. This PR adds them in. Downstream this will be useful since it will allow the RLS to switch over to the goto implementation support that is now standardized.
=> Add server capabilities for 3.6 protocol

src/lib.rs
This makes using `lanugageserver_types` slightly more convenient.
=> Reexport URL

src/notification.rs, src/request.rs
I came across some cases where the `lsp_request!` and `lsp_notification!` macros returned missing types. I also added a couple of tests to help type-check these, and verify the macro names matched the method names.
**Note** that in addition to fixing the macros, I changed the `WillSave` enum to `WillSaveTextDocument` to be more consistent with the others. This has the potential to break crates depending on that enum, so if it's considered too late to change this, I can just fix the macro instead.
=> Macro fixes

README.md, src/lib.rs, src/notification.rs, src/request.rs
This should bump us up to 3.13. It's probably best to review each commit separately.
Supercedes #78 
Fixes #76
=> Support 3.13

src/lib.rs
`MarkedString` and `LanguageString` should derive `Clone`, one use case:
https://github.com/rust-lang/rls/blob/30b86f957e577b349fa3dc6b273f7277227972c7/src/actions/hover.rs#L1026-L1044
r? @Marwes
=> Add `Clone` impl for HoverContents and related

src/lib.rs
So we can more easily hash ids
=> Make NumberOrString Hash

src/lib.rs
According to LSP spec, SignatureHelp::active_parameter and
SignatureHelp::active_signature have type `number` which can have negative
values as well.
Change the type of parameters in the struct from u64 to i64 to allow
de-serializing from servers that set the value of these parameters to -1 to
indicate value that is ignored.
Partially fixes issue #84.
=> lib.rs: Update SignatureHelp parameter types

src/lib.rs, src/request.rs
This is the proposes extension to the protocol, which looks like it's going to be stabilized soon. 
See https://github.com/Microsoft/vscode-languageserver-node/pull/474
Let's not merge the PR until it is set in stone though
=> add proposed selectionRange API

src/lib.rs
Looking at [`textDocument/codeAction`](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) it seems to be returning heterogeneous array `(Command | CodeAction)[] | null` rather than `Command[] | CodeAction[] | null` so I adjusted that accordingly.
Discovered this while working on https://github.com/rust-lang/rls-vscode/issues/609 - right now RLS sends only `Vec<Command>` but to fix the issue we also need send some `CodeAction`s as well, hence why we need the heterogenous array.
r? @Marwes
=> Adjust CodeActionResponse

Cargo.toml, src/lib.rs
Migration to 2018 edition
This was motivated by rust-analyzer interpreting the `std::try` macro as as the `try` keyword and reporting lots of errors.
=> Edition 2018

src/lib.rs
I have a branch of rust-analyzer that uses this at https://github.com/kjeremy/rust-analyzer/tree/flatten
Fixes #82
=> Use #[serde(flatten)] for composition

src/lib.rs
Some clients such as the LSP Support plugin for Jetbrains IDEs use -1 as the first version for text document.
=> Change text document's version to i64 instead of u64

src/lib.rs, src/notification.rs, src/request.rs
The proposed progress support of the protocol was updated, see https://github.com/microsoft/language-server-protocol/issues/786 for details. It is already implemented in the https://github.com/microsoft/vscode-languageserver-node/commit/cd6dcf0e1cf0f8e3b14b78b3322857f6f636ee7d library.
This PR adds all types for the ["Work Done"](https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.progress.proposed.md#reporting-server-task-progress) part of the spec.
=> Update proposed progress support

src/lib.rs
I'm hoping we can future proof a bit by using `..Default::default()` when initializing structs in clients of lsp-types.
=> Add some Default and skip serialize on Options

Cargo.toml, src/lib.rs, src/notification.rs
Adds types for https://github.com/microsoft/vscode-languageserver-node/pull/367
I used this to implement syntactic highlighting in https://github.com/ul/kak-lsp
It also adds the `base64` and `byteorder` crates to parse the semantic tokens.
The `kak-lsp` client has been tested with `clangd`
=> Add proposed syntax highlighting types

src/lib.rs, src/request.rs
Minimum protocol for semantic token proposal for LSP 3.16 and the latest vscode. This is the protocol only and does not provide the helpers needed to encode data as specified here: https://github.com/microsoft/vscode-languageserver-node/blob/8c8981eb4fb6adec27bf1bb5390a0f8f7df2899e/client/src/semanticTokens.proposed.ts#L71-L183 I would like to work that out in rust-analyzer. Once done I will open another PR.
Closes #136
=> Implement proposed semantic token protocol

src/lib.rs
Pretty sure that unsafe code is never going to be a problem with this crate, but it can help a bit when inspecting the `cargo-geiger` output of a dependency tree, and having it in the `lib.rs` gives off a warm, fuzzy feeling.
=> Add #![forbid(unsafe_code)] crate attribute

src/lib.rs
https://github.com/microsoft/vscode-languageserver-node/commit/b382b6ac418afd21805c6173f71559edf97dba8d
We have 'declaration', everything else is a 'reference'
=> Remove references token modifier.

src/notification.rs, src/request.rs
* Updated the `lsp_notification!()` and `lsp_request!()` macros to match the new status of `WaitSaveWaitUntil`.
* Redefine `textDocument/willSaveWaitUntil` as a request.
Fixes #142.
=> Redefine textDocument/willSaveWaitUntil as a request

src/notification.rs, src/request.rs
This will always be true since otherwise there would be no way to
send/receive the params or result.
Fixes #140
=> feat: Add DeserializeOwned + Serialize bounds on request/notifications

src/lib.rs
* Use `DocumentLinkCapabilities` in `TextDocumentClientCapabilities`.
The previous version of the code used `GenericCapability` instead, and the `DocumentLinkCapabilities` type was defined but unused. This should fix support for `textDocument/documentLink` tooltip support for LSP version 3.15.0.
=> Use DocumentLinkCapabilities in TextDocumentClientCapabilities

src/request.rs
* Change `SelectionRangeRequest::Result` associated type from `Vec<SelectionRange>` to `Option<Vec<SelectionRange>>`.
According to the [specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange), the `textDocument/selectionRange` response result type is `SelectionRange[] | null`.
This means that the correct result type should be `Option<Vec<SelectionRange>>`.
=> Fix SelectionRangeRequest::Result type

src/lib.rs, src/notification.rs, src/request.rs
This PR updates the format of the different comments that were probably ported straight from the TypeScript docs to match Rust doc comment style.
=> Update doc comments to match rust style

src/lib.rs
Noticed that `color_provider` is missing the `skip_serializing_if` attribute. As per [the specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize), this value should either not be sent or sent with a non-null value.
This is causing issues in LanguageClient-neovim for some specific servers, see: https://github.com/autozimu/LanguageClient-neovim/issues/940
=> Skip serializing color_provider if None

Cargo.toml
`json::Value` requires `Eq` which wasn't implemented until serde_json 1.0.50
=> Minimum serde_json required to build

src/lib.rs
`TextDocumentSyncOptions.save` can be boolean or `SaveOptions`
Fixes #167
=> Fix TextDocumentSyncOptions.save

src/lib.rs
The `TextDocumentSaveRegistrationOptions` interface is described [in the `textDocument/didSave` section of the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didSave). These options are necessary when registering for the `textDocument/didSave` request. It seems to have existed since v3.0, judging by the GitHub Pages history for the official site.
Found this omission while investigating https://github.com/ebkalderon/tower-lsp/issues/190.
=> Add missing TextDocumentSaveRegistrationOptions struct

src/lib.rs
The `HoverOptions` and `HoverRegistrationOptions` interfaces are described [in the `textDocument/hover` section of the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_hover). These options are necessary when registering the `textDocument/hover` request per-document.
Likewise, the `ServerCapabilities::hover_provider` field is defined in the spec >=3.15 as being:
```ts
/**
* The server provides hover support.
*/
hoverProvider?: boolean | HoverOptions;
```
So I added a `HoverProviderCapability` enum in the spirit of existing `.*ProviderCapability` enums in the project, and I changed `ServerCapabilities::hover_provider` to be `Option<HoverProviderCapability>` accordingly.
All of these changes seem to have existed since v3.15, …
=> Add HoverOptions, HoverRegistrationOptions, HoverProviderCapability

src/lib.rs
```typescript
interface DidSaveTextDocumentParams {
/**
* The document that was saved.
*/
textDocument: TextDocumentIdentifier;
/**
* Optional the content when saved. Depends on the includeText value
* when the save notification was requested.
*/
text?: string;
}
```
https://microsoft.github.io/language-server-protocol/specification#textDocument_didSave
=> Add missing optional text field in DidSaveTextDocumentParams

src/lib.rs
```typescript
export interface ConfigurationItem {
/**
* The scope to get the configuration section for.
*/
scopeUri?: DocumentUri;
/**
* The configuration section asked for.
*/
section?: string;
}
```
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration
=> Fix the type of `ConfigurationItem.scope_uri`

src/lib.rs, src/rename.rs
This PR fixes some fields in the `ServerCapabilities` struct which were not complying with the specification. This was raised as an issue in LanguageClient-neovim [here](https://github.com/autozimu/LanguageClient-neovim/issues/1096). There's two sides to that issue, one of which this PR tries to solve.
Mind you, this PR introduces breaking changes by deleting `RenameProviderCapability` and using `OneOf<bool, RenameOptions>` instead. If you don't believe this is the best option I'm happy to change it to something less generic.
=> Fix specification uncomplying fields in ServerCapabilities struct

src/lib.rs
Fixes the definition of the `workspace_symbol_provider` field in `ServerCapabilities`. See https://github.com/microsoft/language-server-protocol/issues/1109.
=> Fix workspace_symbol_provider definition

src/code_action.rs, src/code_lens.rs, src/color.rs, src/completion.rs, src/folding_range.rs, src/formatting.rs, src/lib.rs, src/notification.rs, src/progress.rs, src/rename.rs, src/request.rs, src/selection_range.rs, src/semantic_tokens.rs, src/signature_help.rs, src/type_rename.rs, src/window.rs
Each commits adds a separate feature.
Adds missing fields in `ApplyWorkspaceEdit`
Uses newly clarified numeric types
Adds `workspace/codeLens/refresh`
Adds `window/showDocument`
Best reviewed by commit.
cc @matklad
=> New proposed features for LSP 3.16, missing fields and clarification on numerics

src/code_action.rs, src/lib.rs, src/rename.rs
Supported in vscode-languageclient 7.0.0-next.14
=> Change annotations and markdown client capabilities

src/lib.rs
After microsoft/language-server-protocol#1147 and rust-analyzer/rust-analyzer#6603, here is the change this will bring to the spec.
=> Fix DidSaveTextDocumentParams::text_document to use TextDocumentIdentifier

src/lib.rs
According to the spec this should be "groupsOnLabel"
See https://github.com/gluon-lang/lsp-types/pull/193#discussion_r546764962
=> Fix "groups_on_labels"

src/lib.rs
Replaced with the comment from the specification.  
I couldn't find any other mistakenly repeated doc comments.
=> Fix wrong doc comment for server_info

src/lib.rs
As of 3.16.0, a [document symbol provider can provide an optional label](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol):
```ts
export interface DocumentSymbolOptions extends WorkDoneProgressOptions {
/**
* A human-readable string that is shown when multiple outlines trees
* are shown for the same document.
*
* @since 3.16.0
*/
label?: string;
}
```
This PR adds the optional `label` field.
=> Add missing label to DocumentSymbolOptions

src/linked_editing.rs
The [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/) says:
interface ServerCapabilities {
...
linkedEditingRangeProvider?: boolean | LinkedEditingRangeOptions
| LinkedEditingRangeRegistrationOptions;
}
Add an enum variant for bool. This is consistent with "FoldingRangeProviderCapability".
Originally reported at https://github.com/kak-lsp/kak-lsp/issues/484
=> Allow plain bool in server capability "linkedEditingRangeProvider"

src/rename.rs
The `default_behaviour` field in `PrepareRenameResponse` is not being renamed to camel_case, see: https://github.com/gluon-lang/lsp-types/blob/master/src/rename.rs#L80
Adding a serde annotation solves this.
=> Fix PrepareRenameResponse casing issue

src/error_codes.rs, src/lib.rs
This pull request adds constants for LSP specific [error codes](https://microsoft.github.io/language-server-protocol/specifications//specification-3-17/#errorCodes), but not for the ones that are part of the JSON RPC specification.
I can add the JSON RPC ones mentioned in the LSP specification if you think that is appropriate?
=> Add constants for lsp specific error codes

src/completion.rs, src/rename.rs
This should bring us inline with vscode June 2021.
=> Update CompletionItemLabelDetails to latest proposal

Cargo.toml
This crate is more complete and better maintained than any of the crates with "lsif" in their name but it doesn't show up in a crates.io search for "lsif". This should fix that.
=> Add "lsif" to keywords.

src/completion.rs, src/lib.rs
=> feat: Add a TryFrom<&str> implementation for enumerations

src/inlay_hint.rs, src/lib.rs
Closes #232 and updates the `inlayHint` code to support the `data` property.  #231 must be merged first.
=> feat: implement json helpers

src/lib.rs, src/notification.rs, src/trace.rs
This adds types for the two missing notifications. See:
* https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#setTrace
* https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#logTrace
It also renames the `TraceOption` type to `TraceValue`, which is the name used in the [LSP specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#traceValue).
Closes #235
=> Add missing $/setTrace and $/logTrace notifications

src/lib.rs
Add Default to the derive for `InitializeParams` so that this struct
can be initialized without compilation warnings / errors about the
deprecated root_path field.
Tested by building something that errored on deprecated fields,
and using this code:
```
let capabilities = ClientCapabilities {
..Default::default()
};
let _init = InitializeParams {
process_id: None,
root_path: None,
root_uri: None,
initialization_options: None,
capabilities,
trace: None,
workspace_folders: None,
client_info: None,
locale: None,
};
```
It did not error after adding the derive and changing to:
```
let capabilities = ClientCapabilities {
..Default::default()
};
let _init = InitializeParams {
capabilities,
..Default::default()
};
```
=> Add Default derive for `InitializeParams`

src/semantic_tokens.rs
Add support for the extensions to [semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens) added in 3.17:
* `decorator` token type
* `serverCancelSupport` client capability
* `augmentsSyntaxTokens` client capability
=> Add semantic tokens 3.17 extensions

src/lib.rs
3.17 introduces `PositionEncodingKind` to indicate how positions are encoded (utf-8, utf-16, or utf-32).  There are also corresponding fields in the client (`positionEncodings`) and server (`positionEncoding`) capabilities to negotiate which to use.
=> Add PositionEncodingKind and friends from 3.17

src/lib.rs
I want to use it [here] for implementing
"workspace/didChangeWatchedFiles", specifically to deduplicate file
change events before I send them to the language server.
[here]: https://github.com/kak-lsp/kak-lsp/pull/650/commits/346123f52fc8a1e450ac522938aac6809f177a0f#diff-1fd48ab302efbb91fe84507671007262db18094467e4ad707d036f60ff22e0eaR92
=> Derive Hash for file change events

README.md, src/code_action.rs, src/completion.rs, src/error_codes.rs, src/folding_range.rs, src/inlay_hint.rs, src/inline_value.rs, src/lib.rs, src/request.rs, src/semantic_tokens.rs, src/type_hierarchy.rs, src/workspace_folders.rs, src/workspace_symbols.rs
* Add support for `textDocument/inlineValue`.
* Add new features to `workspace/symbols` and support `workspaceSymbol/resolve`.
* Add support for HTML tags in `MarkdownClientCapabilities`.
* Add support for collapsed text in folding.
* Add support for trigger kinds in code action requests.
* Add support for position encoding (not sure if safe to remove support for unofficial `UTF8-offsets` extension now?)
* Add support for relative patterns in `FileSystemWatcher`s
* Add support for type hierarchies.
* Stabilize `CodeActionKind::SOURCE_FIX_ALL`.
* Stabilize `LSPAny`, `LSPObject`, and `LSPArray` type aliases.
* Stabilize support for `textDocument/inlayHint`.
* Stabilize all parts of semantic token support marked `proposed`.
* Stabilize completion label item details support.
* Stabilize …
=> Support all new 3.17 features (except for notebooks)

src/request.rs
=> Fix missing `workspaceSymbol/resolve` for `lsp_request!`

src/call_hierarchy.rs, src/code_action.rs, src/code_lens.rs, src/color.rs, src/completion.rs, src/document_highlight.rs, src/document_symbols.rs, src/file_operations.rs, src/folding_range.rs, src/formatting.rs, src/lib.rs, src/lsif.rs, src/progress.rs, src/rename.rs, src/request.rs, src/semantic_tokens.rs, src/signature_help.rs, src/trace.rs, src/window.rs, src/workspace_symbols.rs, tests/lsif.rs
- add some derive for better ergonomics
=> doc: do some doc clean up, fix typo and clippy warning

src/notification.rs
* Changed `Params` for `TelemetryEvent` notification to `OneOf<LSPObject, LSPArray>`.
This pull request fixes a defect in the upstream LSP specification. According to https://github.com/microsoft/language-server-protocol/issues/1686, the `params` field of JSON-RPC message _must_ be of type `object | array`. The specification had previously incorrectly specified `telemetry/event` as having `params` of type `object | number | boolean | string` (basically a `serde_json::Value`) despite this violating the JSON-RPC 2.0 and LSP specs.
=> Fix incorrect params type for TelemetryEvent notification

src/lib.rs
The work done progress token may be present in VSCode client with `LanguageClientOptions { progressOnInitialization: true }`
=> Add support for work done ProgressToken by the initialize request

src/lib.rs
Marks `root_uri` as deprecated. Closes #247
=> fix: Add deprecation note for `rootUri`

src/lib.rs
First of all thanks so much for this project!
As part of some work in [asm-lsp](https://github.com/bergercookie/asm-lsp), I found it would be helpful if the `Hash` trait was derived on the `Location` struct, which I've done in this PR.
I looked through some of the other types defined in this project and saw that some could have `Hash` derived, but others could not as they contain a field of type `serde_json::Value`, which does not implement `Hash`. Is there any downside to deriving this trait when possible? I'd be happy to go through and add `Hash` derives as allowed on all structs in the crate if that would be helpful :)
=> Derive `Hash` for `Location` struct

src/request.rs
The specification has InlineValue[] | null i.e. Option<Vec<InlineValue>>  (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlineValue). We have InlineValue | null i.e. Option<InlineValue>.
=> Fixed incorrect result type for InlineValueRequest
