Cargo.toml
src/lib.rs

There is a bit of other cleanup as well but 88e2565f6b1873b59dc1493c00d1c7166acbb766 is the bulk of the PR.

feat: Bump serde version to 0.9.6

---

Cargo.toml
src/lib.rs

feat: Update the serde dependency to 1.0.0

---

src/lib.rs
src/notification.rs
src/request.rs

See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#new-markupcontent

feat: Add MarkupContent

---

src/lib.rs

See https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textdocumentclientcapabilities-define-capabilities-the-editor--tool-provides-on-text-documents

Add CompletionItemKindCapability

---

src/lib.rs
src/notification.rs

Make WorkspaceEdit compatible with protocol 3.0.

---

src/request.rs

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#completion-request-leftwards_arrow_with_hook

CompletionResponse could be null.

---

src/lib.rs

Affects https://github.com/autozimu/LanguageClient-neovim/issues/287

Adding more CompletionItemKind.

---

src/lib.rs

See https://github.com/rust-lang-nursery/rls/pull/681

Add group field to Diagnostics

---

src/lib.rs

Ref
- https://github.com/autozimu/LanguageClient-neovim/issues/352
- https://github.com/cquery-project/cquery/issues/573

Capturing all unknown SymbolKind enums.

---

README.md
src/lib.rs

Fixes #55.
@Marwes does this look okay?

Support DiagnosticRelatedInformation in LSP 3.7

---

src/lib.rs

Add related information support to  TextDocumentClientCapabilities

---

src/lib.rs

This PR is reqired by 
https://github.com/autozimu/LanguageClient-neovim/pull/514
// cc @autozimu 
I just noticed that I was changing a library without sending PR

Allow CompletionItem to be cloned

---

src/lib.rs

Looks like it was misplaced.
Close #67.

Move completion_item_kind and context_support from HoverCapability to CompletionCapability.

---

src/lib.rs
src/request.rs

closes https://github.com/gluon-lang/languageserver-types/issues/72

Document symbol

---

src/lib.rs
src/notification.rs
src/request.rs

Can someone double check this?
`check_macro!("textDocument/colorPresentation");` fails because of `DeserializeOwned` but I'm not sure what I am doing wrong.
Fixes #75

Support textDocument/{documentColor,colorPresentation}

---

src/request.rs

Specifically:
* `textDocument/implementation`
* `textDocument/typeDefinition`

Update missing requests in lsp_request! macro

---

src/lib.rs
src/request.rs

Adds LocationLink in the appropriate replies, goto declaration request and parameter label ranges.
See: https://microsoft.github.io/language-server-protocol/specification#version_3_14_0

Implement 3.14.0

---

Cargo.toml
README.md

shorter name

---

src/lib.rs

see https://github.com/Microsoft/vscode-languageserver-node/commit/d3de1f8255564bba6775c574ddf06d473ad82579#r31927588
I don't mind holding this off until the protocol change is actually made.

fix LocationLink to match the real world

---

Cargo.toml
src/lib.rs

https://serde.rs/enum-number.html

Use serde_repr for serializing fieldless enums

---

src/lib.rs

Hi, this fixes a bug with the latest published version which prevents server from starting (b/c it can't deserialize initialize message). The seccond commit is cleanup.
It might makes sense to yank 0.63 and publish 0.63.1.

Serde repr everywhere

---

src/lib.rs
src/notification.rs

See: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgressEnd

Rename WorkDoneProgress::Done to End

---

src/lib.rs
src/request.rs

Bring SelectionRange in line with 3.15

---

src/lib.rs

Needed for rust-analyzer/rust-analyzer#2651
vscode currently presents a boolean tagSupport value, while it's a field not coming until the next lsp version (3.15), vscode already presents this value in a stable release, so we should support it.

Add support for boolean tagSupport value since it's present in stable vscode

---

src/lib.rs

See comment:
https://github.com/rust-analyzer/rust-analyzer/issues/2651#issuecomment-568554427
Apparently `default` is needed to handle optional fields with custom de-serialize impls. This also rejects `null` (unless `TagSupport` supports it) which the previous impl didn't.

Fix deserialize for tagSupport if tag is missing and add deserialization tests

---

src/lib.rs
src/request.rs

See https://github.com/rust-analyzer/rust-analyzer/pull/2698 for an example implementation.

Proposed call hierarchy

---

src/lib.rs

PR for #133
I gave it a try, not entirely sure if this is correct.

Make tokens in SemanticHighlightInformation optional

---

src/lib.rs
src/notification.rs

See microsoft/language-server-protocol@a8f763b

Support window/workDoneProgress/cancel notification

---

src/lib.rs

See https://github.com/microsoft/vscode-languageserver-node/commit/63dd4bd967c772f65116cbc9950419dad9d6b23f

Remove volatile and async semantic token modifiers

---

src/lib.rs

Serialize tokens with a slice

---

src/lib.rs

[DocumentLink](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentLink) spec

Updated DocumentLink fields to make tooltip optional and added data field

---

src/lib.rs

Move CodeActionKind to the same pattern as SemanticTokenType

---

src/lib.rs
src/request.rs

Brings us in line with vscode-languageclient 7.0.0-next.9
Tested with rust-analyzer.

Move to latest SemanticTokens proposal

---

src/semantic_tokens.rs

See https://github.com/microsoft/language-server-protocol/issues/1087

Member is now Method to avoid confusion

---

README.md

Updates version and add note about proposed features

---

src/completion.rs

Add missing commit_characters to CompletionItem

---

src/lib.rs
src/lsif.rs
src/request.rs
src/semantic_tokens.rs

After running cargo doc on source I see some warnings. This PR addresses them.

fix cargo doc warnings

---

src/request.rs

Fix `SemanticTokensRefresh` typo

---

src/inlay_hint.rs
src/lib.rs
src/request.rs

See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification
Closes #230

feat(inlayHint): implement inlayHint

---

src/lib.rs

For consistency with other documentation.

capitalization
